name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar o Build do Eleventy
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Fazer Upload dos artefatos (pasta _site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Fazer o Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
